// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in golang-ent-gqlgen-example/ent/runtime.go

const (
	Version = "(devel)" // Version of ent codegen.
)
